### ISSUE TITLE
Please add Readme.MD

### ISSUE THREAD

**Issue by dcampogiani** [azanin/fpInScala#1]
Please add Readme.MD with comment for each exercise.

**Comment by azanin** [comment]
I will.

Il giorno mer 27 gen 2016 14:43 Daniele Campogiani notifications@github.com
ha scritto:

**Comment by dcampogiani** [comment]
Ping.

**Comment by dcampogiani** [comment]
Any update?

**Comment by dcampogiani** [comment]
Ping.
